baseURL: "https://santiberna.github.io/"
languageCode: "en-us"
title: "Santiago Bernardino - Game Engine Programmer"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    - identifier: resume
      name: Resume
      title: Resume
      url: "/resume.pdf"
      weight: 1
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Santiago Bernardino - Game Engine Programmer"
  description: "I develop game engines and tools using C++. Experience with scripting systems, multithreading, content pipelines and cross platform design. Passionate about developing effective and clear APIs, tools and systems."
  staticPath: ""  # The path to serve the static files from
  favicon: "/images/octahedron2.svg"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark"

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  color:
    textColor: "#cfd5e2"
    secondaryTextColor: "#6c757d"
    textLinkColor: "#007bff"
    backgroundColor: "#eaedf0"
    secondaryBackgroundColor: "#64ffda1a"
    primaryColor: "#007bff"
    secondaryColor: "#f8f9fa"

    darkmode:
      textColor: "#D2DEEC"
      secondaryTextColor: "#b0b3b8"
      textLinkColor: "#FFFFFF"
      backgroundColor: "#18191a"
      secondaryBackgroundColor: "#212529"
      primaryColor: "#E2EAF4"
      secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    brandLogo: "/images/octahedron2.svg" # Logo for the brand | default is the favicon variable
    showBrandLogo: true # Show brand logo in nav bar | default is true
    brandName: "Santiago Bernardino" # Brand name for the brand | default is the title variable
    disableSearch: false
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : false
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: true
      disableEducation: false
      disableProjects: false
      disableAchievements: true
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Santiago Bernardino"
    subtitle: "Game Engine and Tools Programmer"
    content: "I develop game engines and tools using C++. Experience with scripting systems, multithreading, content pipelines and cross platform design. Passionate about working on simple and effective APIs that give other developers a sigh of relief."
    # image: /images/blossom/poi.gif
    # roundImage: true # Make hero image circular | default false
    bottomImage:
      enable: false
  
    button:
      enable: true
      name: "Check out my Projects!"
      url: "#projects"
      download: false
      newPage: false
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/santiberna
        - icon: fab fa-linkedin
          url: https://linkedin.com/in/santiago-bernardino

  # About
  about:
    enable: true
    title: "About Me"
    image: /images/hero.jpg
    content: |-
      Hello there! I'm a 3rd-year Game Programming student at BUAS. I am a passionate developer with a strong background on C++ and problem solving, **currently looking for an internship on engine programming and/or tool development, starting September 2025.**

      **I've contributed to two custom game engines** for team projects and gained hands-on experience with **integrating scripting, networking, 3D model loading, and multithreading**. I'm also familiar with **Scrum/Agile workflows**.

      Obviously, I also play games in my free time: I believe they are one of the most immersive forms of media nowadays and I am proud to work in something that has been very important in my life.
      Outside of programming and games, I'm passionate about music (currently learning drums) and was once a national fencing champion in high school. My hobbies are a big part of how I channel creativity into everything I do.
    skills:
      enable: false
      title: |-
        Here are some tools and libraries that I am familiar with:
      items:
        - "C++"
        - "Visual Studio"
        - "VSCode"
        - "CMake"
        - "Git and Github"
        - "Perforce"
        - "SDL"
        - "Boost.Asio"
        - "OpenGL"

  # Experience
  # experience:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - job: "UI/UX Designer"
  #       company: "Netflix"
  #       companyUrl: "https://example.com"
  #       date: "June 2017 - Nov 2019"
  #       featuredLink:
  #         enable: true
  #         url: "https://example.com"
  #       content: |
  #         I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city.

  #         - Lead backend developer for a product.
  #         - Created a frontend design for a product.

  #     - job: "Product Designer"
  #       company: "Google"
  #       companyUrl: "https://example.com"
  #       date: "Feb 2016 - Mar 2017"
  #       content: "I am currently working as a software developer at [example org.](https://example.com) in San Francisco, CA. I am currently working on a project that will be used to help people find the best way to get around the city."

  # # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "Bachelor of Creative Media and Game Technologies - Programming"
        school:
          name: "Breda University of Applied Sciences, Netherlands"
          url: "https://www.buas.nl"
        date: "2022 - Now"
        content: |-
          Learned essential aspects of game development such as
            - C++ and modern programming paradigms and patterns
            - Scrum workflow and how to work as a team
            - Graphics, networking, 3D math for games, optimization, multithreading, etc...

  # Achievements
  # achievements:
  #   enable: true
  #   # title: "Custom Name"
  #   items:
  #     - title: Google kickstart runner
  #       content: I solved all problems with optimal solution.
  #       url: https://example.com
  #       image: /images/achievment.jpg

  # projects
  projects:
    enable: true
    # title: "Custom Name"

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: If you want to contact me, simply message me on LinkedIn or shoot me an email **santibberna@gmail.com**. I will be happy to answer!
    # btnName: My Resume
    # btnLink: "SantiagoResume.pdf"
    # formspree:
    #   enable: true # `contact.email` value will be ignored
    #   formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
    #   emailCaption: "Enter your email address"
    #   messageCaption: "Enter your message here"
    #   messageRows: 5

  footer:
    recentPosts:
      path: "posts"
      count: 3
      title: Recent Posts
      enable: false
      disableFeaturedImage: false
    socialNetworks:
      github: https://github.com/santiberna
      linkedin: https://linkedin.com/in/santiago-bernardino

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: false
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
